<?php 
define ('CNF_DOMAIN', 'sximo.io');
define ('CNF_APPNAME', 'Sximo 5 - Reloaded');
define ('CNF_APPDESC', 'PHP Application Builder ');
define ('CNF_COMNAME', 'My Company name');
define ('CNF_EMAIL', 'info@mycompanyname.com');
define ('CNF_CONTACTEMAIL', 'contact@mycompanyname.com');
define ('CNF_CONTACTEMAIL2', 'contact2@mycompanyname.com');
define ('CNF_CONTACTEMAIL3', 'contact3@mycompanyname.com');
define ('CNF_METAKEY', 'my site , my company  , Laravel Crud');
define ('CNF_METADESC', 'Write description for your site');
define ('CNF_GROUP', '3');
define ('CNF_ACTIVATION', 'confirmation');
define ('CNF_MULTILANG', '1');
define ('CNF_LANG', 'en');
define ('CNF_REGIST', 'true');
define ('CNF_FRONT', 'true');
define ('CNF_RECAPTCHA', 'false');
define ('CNF_THEME', 'elliot');
define ('CNF_RECAPTCHAPUBLICKEY', '');
define ('CNF_RECAPTCHAPRIVATEKEY', '');
define ('CNF_MODE', 'production');
define ('CNF_LOGO', 'backend-logo.png');
define ('CNF_ALLOWIP', '');
define ('CNF_RESTRICIP', '192.116.134 , 194.111.606.21 ');